# Generated by Django 5.2.11 on 2026-02-26 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BacktestRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbols", models.CharField(max_length=500)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "initial_capital",
                    models.DecimalField(
                        decimal_places=2, default=10000.0, max_digits=12
                    ),
                ),
                (
                    "commission_pct",
                    models.DecimalField(decimal_places=5, default=0.001, max_digits=6),
                ),
                (
                    "commission_fixed",
                    models.DecimalField(decimal_places=2, default=1.0, max_digits=6),
                ),
                ("strategy_config", models.JSONField()),
                (
                    "final_portfolio_value",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("total_return", models.DecimalField(decimal_places=6, max_digits=8)),
                (
                    "annualized_return",
                    models.DecimalField(decimal_places=6, max_digits=8),
                ),
                (
                    "annualized_volatility",
                    models.DecimalField(decimal_places=6, max_digits=8),
                ),
                ("sharpe_ratio", models.DecimalField(decimal_places=4, max_digits=8)),
                ("sortino_ratio", models.DecimalField(decimal_places=4, max_digits=8)),
                ("max_drawdown", models.DecimalField(decimal_places=6, max_digits=8)),
                ("equity_curve", models.JSONField(blank=True, null=True)),
                ("drawdown_curve", models.JSONField(blank=True, null=True)),
                ("daily_returns", models.JSONField(blank=True, null=True)),
                ("portfolio_values", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "backtest_runs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Trade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(max_length=10)),
                (
                    "trade_type",
                    models.CharField(
                        choices=[("BUY", "Buy"), ("SELL", "Sell")], max_length=4
                    ),
                ),
                ("date", models.DateField()),
                ("price", models.DecimalField(decimal_places=4, max_digits=12)),
                ("shares", models.DecimalField(decimal_places=4, max_digits=12)),
                ("commission", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "backtest_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trades",
                        to="financer.backtestrun",
                    ),
                ),
            ],
            options={
                "db_table": "trades",
                "ordering": ["date"],
            },
        ),
    ]
